title: "Déguisements pour toutes les occasions : Halloween, EVJF, anniversaires, EVG"
email: deguisement.fun@gmail.com
timezone: UTC
url: "www.deguisement.fun"
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'www-deguisement-fun'
locale: fr
lang: fr
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-CXVY4MDFDT


# Authors
authors:
  zoe:
    name: Zoé déguisements
    display_name: Zoé déguisement
    avatar: 'assets/images/sal.png'
    email: deguisement.fun@gmail.com
    web: https://www.deguisement.fun
    twitter: https://twitter.com/Deguisementfun
    description: "Trouvez le déguisement parfait pour votre prochaine fête grâce à notre blog de déguisements. Que ce soit pour Halloween, un anniversaire, un EVJF, un EVG ou toute autre occasion, nous avons rassemblé pour vous les meilleures idées de déguisements pour tous les budgets et styles."
  
# Social
social:
  instagram: https://www.instagram.com/deguisement.fun/
  facebook: https://www.facebook.com/profile.php?id=100089125362385
  twitter: https://twitter.com/Deguisementfun

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives